### ISSUE TITLE
Waiting for the code

### ISSUE THREAD

**Issue by Lwzzzzzz** [chongweiliu/PuTR#1]
Hi, congratulations for your great work! Look forward to access the code as soon as possible.

**Comment by chongweiliu** [comment]
We apologize for the considerable delay in releasing our open-source code and pre-trained models. Due to our involvement in other research endeavors, the public dissemination of these resources was regrettably postponed. However, we are pleased to announce that the code and models are now available for use. We encourage the community to leverage these materials and welcome any feedback or contributions.

**Comment by Lwzzzzzz** [comment]
Thanks!
