### ISSUE TITLE
A little question about FPS after the data type is switched to fp16

### ISSUE THREAD

**Issue by liaopan-lp** [chongweiliu/PuTR#3]
Very good job. Thank you for sharing the code. 
 
My test environment is 13900k+4090. When I tested the fps, the result was slightly worse than that in your paper (this is not important). However, after switching the model and data to fp16, the fps was similar to that when the model was fp32. When I tested MOTIP before, switching it to fp16 can increase the fps by about 1.3 times, but putr has almost no improvement. This makes me a little confused. Do you know why? 
 
We look forward to your reply! Happy programming!

**Comment by chongweiliu** [comment]
Thank you for approving my work. 

The question is actually quite simple to explain. DETR-based models like MOTIP have their main computational power requirement concentrated in the object detection part (in the structure of DETR), while the computational power required for tracking is basically negligible. From this point of view, the power required by PUTR is basically equal to that of the tracking part of MOTIP, and because of its low power requirement, putr itself is not a bottleneck in the whole tracking system, for changing the data format will not have a significant impact on the speed.

**Comment by liaopan-lp** [comment]
> Thank you for approving my work.
> 
> The question is actually quite simple to explain. DETR-based models like MOTIP have their main computational power requirement concentrated in the object detection part (in the structure of DETR), while the computational power required for tracking is basically negligible. From this point of view, the power required by PUTR is basically equal to that of the tracking part of MOTIP, and because of its low power requirement, putr itself is not a bottleneck in the whole tracking system, for changing the data format will not have a significant impact on the speed.

Good perspective. Due to personal health reasons, I am very sorry for taking so many days to thank you for your reply. You are right. The main reason is that putr is a lightweight network, so under the condition of low load (bz=1), there is no significant difference between FP16 and FP32. I tried to increase the input bz, and when bz is equal to 4, the difference between fp32 and fp16 becomes apparent. 
 
Thank you for your reply. Have a nice day!
